# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				axolotl = true
				bee = true
				cow = true
				magma_cube = true
				pig = true
				skeleton = true
				bat = true
				hoglin = true
				rabbit = true
				silverfish = true
				drowned = true
				experience_orb = true
				dolphin = true
				item = true
				turtle = true
				salmon = true
				wither_skeleton = true
				horse = true
				ender_dragon = true
				glow_squid = true
				glow_item_frame = false
				squid = true
				parrot = true
				creeper = true
				enderman = true
				chicken = true
				donkey = true
				fox = true
				chest_minecart = true
				tropical_fish = true
				slime = true
				iron_golem = true
				zombified_piglin = true
				piglin = true
				blaze = true
				cat = true
				zombie = true
				ghast = true
				sheep = true
				player = true
				pufferfish = true
				eye_of_ender = true
				wolf = true
				villager = true
				zombie_villager = true
				boat = true
				strider = true
				witch = true
				cod = true
				spider = true

			[light_sources.settings.entities.creeperoverhaul]
				bamboo_creeper = true
				desert_creeper = true
				jungle_creeper = true
				dripstone_creeper = true
				cave_creeper = true
				savannah_creeper = true

			[light_sources.settings.entities.friendsandfoes]
				glare = true

			[light_sources.settings.entities.tinyskeletons]
				baby_skeleton = true

